services:
  - type: web
    name: KrishiMitra
    runtime: python
    rootDir: backend_unified
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --workers 2 --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GEMINI_API_KEY
        sync: false
