import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:sizer/sizer.dart';

import '../../core/language_provider.dart';
import '../../core/app_export.dart';
import '../../widgets/custom_app_bar.dart';
import '../../widgets/custom_icon_widget.dart';
import '../../widgets/custom_bottom_bar.dart';
import '../main_shell/main_shell_screen.dart';

class SchemesListScreen extends StatelessWidget {
  const SchemesListScreen({super.key});

  // 🔹 All schemes list
  final List<Map<String, dynamic>> schemes = const [
    {
  'sr': '01',
  'id': 'pm_kisan',
  'title_en': 'PM-KISAN',
  'title_hi': 'प्रधानमंत्री किसान सम्मान निधि',
  'subtitle_en': 'Income Support Scheme',
  'subtitle_hi': 'आय सहायता योजना',
  'icon': 'account_balance',
},
{
  'sr': '02',
  'id': 'pm_fasal_bima',
  'title_en': 'Pradhan Mantri Fasal Bima Yojana',
  'title_hi': 'प्रधानमंत्री फसल बीमा योजना',
  'subtitle_en': 'Crop Insurance',
  'subtitle_hi': 'फसल बीमा',
  'icon': 'shield',
},
{
  'sr': '03',
  'id': 'mksy_rajasthan',
  'title_en': 'Mukhyamantri Kisan Sahayata Yojana',
  'title_hi': 'मुख्यमंत्री किसान सहायता योजना',
  'subtitle_en': 'Farmer Assistance',
  'subtitle_hi': 'किसान सहायता',
  'icon': 'eco',
},
{
  'sr': '04',
  'id': 'rgkssy',
  'title_en': 'Rajiv Gandhi Krishak Saathi Sahayata Yojana',
  'title_hi': 'राजीव गांधी कृषक साथी सहायता योजना',
  'subtitle_en': 'Farmer Welfare',
  'subtitle_hi': 'किसान कल्याण',
  'icon': 'groups',
},
{
  'sr': '05',
  'id': 'kcc',
  'title_en': 'Kisan Credit Card',
  'title_hi': 'किसान क्रेडिट कार्ड',
  'subtitle_en': 'Easy Crop Loan',
  'subtitle_hi': 'आसान कृषि ऋण',
  'icon': 'credit_card',
},
{
  'sr': '06',
  'id': 'interest_subsidy',
  'title_en': 'Interest Subvention Scheme',
  'title_hi': 'ब्याज अनुदान योजना',
  'subtitle_en': 'Interest Relief',
  'subtitle_hi': 'ब्याज राहत',
  'icon': 'percent',
},
{
  'sr': '07',
  'id': 'krishi_saathi',
  'title_en': 'Mukhyamantri Krishi Saathi Yojana',
  'title_hi': 'मुख्यमंत्री कृषि साथी योजना',
  'subtitle_en': 'Agriculture Support',
  'subtitle_hi': 'कृषि सहायता',
  'icon': 'handshake',
},
{
  'sr': '08',
  'id': 'input_subsidy',
  'title_en': 'Krishi Input Subsidy Yojana',
  'title_hi': 'कृषि इनपुट सब्सिडी योजना',
  'subtitle_en': 'Seed & Input Support',
  'subtitle_hi': 'बीज व इनपुट सहायता',
  'icon': 'inventory',
},
{
  'sr': '09',
  'id': 'pm_kisan_maandhan',
  'title_en': 'PM Kisan Maandhan Yojana',
  'title_hi': 'प्रधानमंत्री किसान मानधन योजना',
  'subtitle_en': 'Pension Scheme',
  'subtitle_hi': 'पेंशन योजना',
  'icon': 'elderly',
},
{
  'sr': '10',
  'id': 'sahkari_kalyan',
  'title_en': 'Sahkari Kisan Kalyan Yojana',
  'title_hi': 'सहकारी किसान कल्याण योजना',
  'subtitle_en': 'Cooperative Support',
  'subtitle_hi': 'सहकारी सहायता',
  'icon': 'diversity_3',
},
{
  'sr': '11',
  'id': 'pmksy',
  'title_en': 'Pradhan Mantri Krishi Sinchai Yojana',
  'title_hi': 'प्रधानमंत्री कृषि सिंचाई योजना',
  'subtitle_en': 'Irrigation Scheme',
  'subtitle_hi': 'सिंचाई योजना',
  'icon': 'water_drop',
},
{
  'sr': '12',
  'id': 'pmksy_micro',
  'title_en': 'PMKSY – Per Drop More Crop',
  'title_hi': 'पीएमकेएसवाई – प्रति बूंद अधिक फसल',
  'subtitle_en': 'Micro Irrigation',
  'subtitle_hi': 'सूक्ष्म सिंचाई',
  'icon': 'opacity',
},
{
  'sr': '13',
  'id': 'pmksy_water',
  'title_en': 'PMKSY – Water Harvesting',
  'title_hi': 'पीएमकेएसवाई – जल संरक्षण',
  'subtitle_en': 'Water Conservation',
  'subtitle_hi': 'जल संरक्षण',
  'icon': 'waves',
},
{
  'sr': '14',
  'id': 'nmsa',
  'title_en': 'National Mission for Sustainable Agriculture',
  'title_hi': 'राष्ट्रीय सतत कृषि मिशन',
  'subtitle_en': 'Sustainable Farming',
  'subtitle_hi': 'सतत खेती',
  'icon': 'recycling',
},
{
  'sr': '15',
  'id': 'urja_subsidy',
  'title_en': 'Mukhyamantri Kisan Urja Subsidy Yojana',
  'title_hi': 'मुख्यमंत्री किसान ऊर्जा सब्सिडी योजना',
  'subtitle_en': 'Energy Subsidy',
  'subtitle_hi': 'ऊर्जा सब्सिडी',
  'icon': 'bolt',
},
{
  'sr': '16',
  'id': 'pm_kusum',
  'title_en': 'PM-KUSUM Solar Pump Subsidy',
  'title_hi': 'पीएम-कुसुम सोलर पंप सब्सिडी',
  'subtitle_en': 'Solar Pump',
  'subtitle_hi': 'सोलर पंप',
  'icon': 'solar_power',
},
{
  'sr': '17',
  'id': 'tubewell',
  'title_en': 'Well / Tubewell Construction Scheme',
  'title_hi': 'कुआं / ट्यूबवेल निर्माण योजना',
  'subtitle_en': 'Irrigation Facility',
  'subtitle_hi': 'सिंचाई सुविधा',
  'icon': 'construction',
},
{
  'sr': '18',
  'id': 'farm_pond',
  'title_en': 'Farm Pond Subsidy',
  'title_hi': 'फार्म पॉन्ड सब्सिडी',
  'subtitle_en': 'Water Storage',
  'subtitle_hi': 'जल भंडारण',
  'icon': 'water',
},
{
  'sr': '19',
  'id': 'canal_lining',
  'title_en': 'Canal Lining Scheme',
  'title_hi': 'नहर लाइनिंग योजना',
  'subtitle_en': 'Canal Improvement',
  'subtitle_hi': 'नहर सुधार',
  'icon': 'timeline',
},
{
  'sr': '20',
  'id': 'water_efficiency',
  'title_en': 'Water Use Efficiency Promotion',
  'title_hi': 'जल उपयोग दक्षता योजना',
  'subtitle_en': 'Efficient Water Use',
  'subtitle_hi': 'जल दक्षता',
  'icon': 'invert_colors',
},
{
  'sr': '21',
  'id': 'farm_mechanization',
  'title_en': 'Farm Mechanization Subsidy Scheme',
  'title_hi': 'कृषि यंत्रीकरण सब्सिडी योजना',
  'subtitle_en': 'Machinery Subsidy',
  'subtitle_hi': 'मशीनरी सब्सिडी',
  'icon': 'precision_manufacturing',
},
{
  'sr': '22',
  'id': 'chc',
  'title_en': 'Custom Hiring Centre (CHC)',
  'title_hi': 'कस्टम हायरिंग सेंटर',
  'subtitle_en': 'Machinery on Rent',
  'subtitle_hi': 'मशीन किराया',
  'icon': 'factory',
},
{
  'sr': '23',
  'id': 'tarbandi',
  'title_en': 'Tarbandi Yojana',
  'title_hi': 'तारबंदी योजना',
  'subtitle_en': 'Field Fencing',
  'subtitle_hi': 'खेत तारबंदी',
  'icon': 'fence',
},
{
  'sr': '24',
  'id': 'rkvy',
  'title_en': 'Rashtriya Krishi Vikas Yojana',
  'title_hi': 'राष्ट्रीय कृषि विकास योजना',
  'subtitle_en': 'Agri Development',
  'subtitle_hi': 'कृषि विकास',
  'icon': 'trending_up',
},
{
  'sr': '25',
  'id': 'pkvy',
  'title_en': 'Paramparagat Krishi Vikas Yojana',
  'title_hi': 'परंपरागत कृषि विकास योजना',
  'subtitle_en': 'Organic Farming',
  'subtitle_hi': 'जैविक खेती',
  'icon': 'grass',
},
{
  'sr': '26',
  'id': 'nhm',
  'title_en': 'National Horticulture Mission',
  'title_hi': 'राष्ट्रीय बागवानी मिशन',
  'subtitle_en': 'Horticulture Support',
  'subtitle_hi': 'बागवानी सहायता',
  'icon': 'local_florist',
},
{
  'sr': '27',
  'id': 'warehouse',
  'title_en': 'Warehouse / Cold Storage Subsidy',
  'title_hi': 'गोदाम / कोल्ड स्टोरेज सब्सिडी',
  'subtitle_en': 'Storage Support',
  'subtitle_hi': 'भंडारण सहायता',
  'icon': 'warehouse',
},
{
  'sr': '28',
  'id': 'agroforestry',
  'title_en': 'Sub-Mission on Agroforestry',
  'title_hi': 'कृषि वानिकी उप-मिशन',
  'subtitle_en': 'Tree Based Farming',
  'subtitle_hi': 'वृक्ष आधारित खेती',
  'icon': 'park',
},
{
  'sr': '29',
  'id': 'fpo',
  'title_en': 'Farmer Producer Organisation',
  'title_hi': 'किसान उत्पादक संगठन',
  'subtitle_en': 'Farmer Groups',
  'subtitle_hi': 'किसान समूह',
  'icon': 'groups',
},
{
  'sr': '30',
  'id': 'negpa',
  'title_en': 'National e-Governance Plan – Agriculture',
  'title_hi': 'राष्ट्रीय ई-गवर्नेंस योजना – कृषि',
  'subtitle_en': 'Digital Agriculture',
  'subtitle_hi': 'डिजिटल कृषि',
  'icon': 'computer',
},
{
  'sr': '31',
  'id': 'pashudhan_health',
  'title_en': 'Pashudhan Nishulk Arogya Yojana',
  'title_hi': 'पशुधन निशुल्क आरोग्य योजना',
  'subtitle_en': 'Free Animal Health',
  'subtitle_hi': 'निःशुल्क पशु स्वास्थ्य',
  'icon': 'pets',
},
{
  'sr': '32',
  'id': 'bhamashah_pashu_bima',
  'title_en': 'Bhamashah Pashu Bima / Avika Kavach',
  'title_hi': 'भामाशाह पशु बीमा / अविका कवच',
  'subtitle_en': 'Animal Insurance',
  'subtitle_hi': 'पशु बीमा',
  'icon': 'health_and_safety',
},
{
  'sr': '33',
  'id': 'rashtriya_gokul',
  'title_en': 'Rashtriya Gokul Mission',
  'title_hi': 'राष्ट्रीय गोकुल मिशन',
  'subtitle_en': 'Cattle Development',
  'subtitle_hi': 'गोवंश विकास',
  'icon': 'pets',
},
{
  'sr': '34',
  'id': 'nlm',
  'title_en': 'National Livestock Mission',
  'title_hi': 'राष्ट्रीय पशुधन मिशन',
  'subtitle_en': 'Livestock Support',
  'subtitle_hi': 'पशुधन सहायता',
  'icon': 'agriculture',
},
{
  'sr': '35',
  'id': 'deds',
  'title_en': 'Dairy Entrepreneurship Development Scheme',
  'title_hi': 'डेयरी उद्यमिता विकास योजना',
  'subtitle_en': 'Dairy Business',
  'subtitle_hi': 'डेयरी व्यवसाय',
  'icon': 'storefront',
},
{
  'sr': '36',
  'id': 'fodder_seed',
  'title_en': 'Fodder Seed Production Incentive Scheme',
  'title_hi': 'चारा बीज उत्पादन प्रोत्साहन योजना',
  'subtitle_en': 'Fodder Support',
  'subtitle_hi': 'चारा सहायता',
  'icon': 'grass',
},
{
  'sr': '37',
  'id': 'pmmsy',
  'title_en': 'Pradhan Mantri Matsya Sampada Yojana',
  'title_hi': 'प्रधानमंत्री मत्स्य संपदा योजना',
  'subtitle_en': 'Fisheries Development',
  'subtitle_hi': 'मत्स्य विकास',
  'icon': 'set_meal',
},
{
  'sr': '38',
  'id': 'pashu_aahar',
  'title_en': 'Pashu Aahar Subsidy',
  'title_hi': 'पशु आहार सब्सिडी',
  'subtitle_en': 'Animal Feed Support',
  'subtitle_hi': 'पशु आहार सहायता',
  'icon': 'restaurant',
},
{
  'sr': '39',
  'id': 'pashu_ambulance',
  'title_en': 'Pashu Ambulance Service',
  'title_hi': 'पशु एम्बुलेंस सेवा',
  'subtitle_en': 'Emergency Animal Care',
  'subtitle_hi': 'आपात पशु सेवा',
  'icon': 'local_hospital',
},
{
  'sr': '40',
  'id': 'milk_incentive',
  'title_en': 'Milk Producer Incentive Scheme',
  'title_hi': 'दूध उत्पादक प्रोत्साहन योजना',
  'subtitle_en': 'Milk Bonus',
  'subtitle_hi': 'दूध बोनस',
  'icon': 'emoji_food_beverage',
},
{
  'sr': '41',
  'id': 'beej_swavlamban',
  'title_en': 'Mukhyamantri Beej Swavlamban Yojana',
  'title_hi': 'मुख्यमंत्री बीज स्वावलंबन योजना',
  'subtitle_en': 'Seed Self Reliance',
  'subtitle_hi': 'बीज स्वावलंबन',
  'icon': 'spa',
},
{
  'sr': '42',
  'id': 'nfsm',
  'title_en': 'National Food Security Mission',
  'title_hi': 'राष्ट्रीय खाद्य सुरक्षा मिशन',
  'subtitle_en': 'Food Grain Production',
  'subtitle_hi': 'खाद्यान्न उत्पादन',
  'icon': 'grain',
},
{
  'sr': '43',
  'id': 'beej_gram',
  'title_en': 'Beej Gram Yojana',
  'title_hi': 'बीज ग्राम योजना',
  'subtitle_en': 'Seed Village',
  'subtitle_hi': 'बीज ग्राम',
  'icon': 'nature',
},
{
  'sr': '44',
  'id': 'pmfme',
  'title_en': 'PMFME Micro Food Processing Scheme',
  'title_hi': 'पीएमएफएमई सूक्ष्म खाद्य प्रसंस्करण योजना',
  'subtitle_en': 'Food Processing',
  'subtitle_hi': 'खाद्य प्रसंस्करण',
  'icon': 'factory',
},
{
  'sr': '45',
  'id': 'kisan_kaleva',
  'title_en': 'Kisan Kaleva Yojana',
  'title_hi': 'किसान कलेवा योजना',
  'subtitle_en': 'Farmer Welfare',
  'subtitle_hi': 'किसान कल्याण',
  'icon': 'restaurant_menu',
},
{
  'sr': '46',
  'id': 'e_nam',
  'title_en': 'e-NAM',
  'title_hi': 'ई-नाम',
  'subtitle_en': 'National Agriculture Market',
  'subtitle_hi': 'राष्ट्रीय कृषि बाजार',
  'icon': 'store',
},
{
  'sr': '47',
  'id': 'mandi_fee',
  'title_en': 'Mandi Fee Waiver Scheme',
  'title_hi': 'मंडी शुल्क माफी योजना',
  'subtitle_en': 'Fee Exemption',
  'subtitle_hi': 'शुल्क छूट',
  'icon': 'money_off',
},
{
  'sr': '48',
  'id': 'coop_crop_loan',
  'title_en': 'Cooperative Crop Loan (Zero Interest)',
  'title_hi': 'सहकारी फसल ऋण (शून्य ब्याज)',
  'subtitle_en': 'Interest Free Loan',
  'subtitle_hi': 'ब्याज मुक्त ऋण',
  'icon': 'account_balance_wallet',
},
{
  'sr': '49',
  'id': 'krishi_gyaan',
  'title_en': 'Krishi Gyaan Dhara',
  'title_hi': 'कृषि ज्ञान धारा',
  'subtitle_en': 'Farmer Knowledge',
  'subtitle_hi': 'कृषि ज्ञान',
  'icon': 'menu_book',
},
{
  'sr': '50',
  'id': 'biogas',
  'title_en': 'Biogas Unit Subsidy',
  'title_hi': 'बायोगैस यूनिट सब्सिडी',
  'subtitle_en': 'Clean Energy',
  'subtitle_hi': 'स्वच्छ ऊर्जा',
  'icon': 'eco',
},
{
  'sr': '51',
  'id': 'ig_canal',
  'title_en': 'Indira Gandhi Canal Farmer Welfare Scheme',
  'title_hi': 'इंदिरा गांधी नहर किसान कल्याण योजना',
  'subtitle_en': 'Canal Area Support',
  'subtitle_hi': 'नहर क्षेत्र सहायता',
  'icon': 'water',
},
{
  'sr': '52',
  'id': 'mksp',
  'title_en': 'Mahila Kisan Sashaktikaran Pariyojana',
  'title_hi': 'महिला किसान सशक्तिकरण परियोजना',
  'subtitle_en': 'Women Farmers',
  'subtitle_hi': 'महिला किसान',
  'icon': 'female',
},
{
  'sr': '53',
  'id': 'mahila_participation',
  'title_en': 'Mahila Kisan Participation Scheme',
  'title_hi': 'महिला किसान सहभागिता योजना',
  'subtitle_en': 'Women Participation',
  'subtitle_hi': 'महिला सहभागिता',
  'icon': 'groups',
},
{
  'sr': '54',
  'id': 'pmsby',
  'title_en': 'Pradhan Mantri Suraksha Bima Yojana',
  'title_hi': 'प्रधानमंत्री सुरक्षा बीमा योजना',
  'subtitle_en': 'Accident Insurance',
  'subtitle_hi': 'दुर्घटना बीमा',
  'icon': 'security',
},
{
  'sr': '55',
  'id': 'pmjjby',
  'title_en': 'Pradhan Mantri Jeevan Jyoti Bima Yojana',
  'title_hi': 'प्रधानमंत्री जीवन ज्योति बीमा योजना',
  'subtitle_en': 'Life Insurance',
  'subtitle_hi': 'जीवन बीमा',
  'icon': 'favorite',
},
{
  'sr': '56',
  'id': 'apy',
  'title_en': 'Atal Pension Yojana',
  'title_hi': 'अटल पेंशन योजना',
  'subtitle_en': 'Pension Scheme',
  'subtitle_hi': 'पेंशन योजना',
  'icon': 'elderly',
},
{
  'sr': '57',
  'id': 'agr3',
  'title_en': 'AGR-3 ST Farm Mechanization',
  'title_hi': 'एजीआर-3 एसटी कृषि यंत्रीकरण',
  'subtitle_en': 'ST Mechanization',
  'subtitle_hi': 'एसटी यंत्रीकरण',
  'icon': 'build',
},
{
  'sr': '58',
  'id': 'agr4',
  'title_en': 'AGR-4 SC Farm Mechanization',
  'title_hi': 'एजीआर-4 एससी कृषि यंत्रीकरण',
  'subtitle_en': 'SC Mechanization',
  'subtitle_hi': 'एससी यंत्रीकरण',
  'icon': 'build_circle',
},
{
  'sr': '59',
  'id': 'yantra',
  'title_en': 'Krishi Yantra Subsidy Scheme',
  'title_hi': 'कृषि यंत्र सब्सिडी योजना',
  'subtitle_en': 'Farm Equipment',
  'subtitle_hi': 'कृषि यंत्र',
  'icon': 'precision_manufacturing',
},
{
  'sr': '60',
  'id': 'soil_health',
  'title_en': 'Soil Health Card',
  'title_hi': 'मृदा स्वास्थ्य कार्ड',
  'subtitle_en': 'Soil Testing',
  'subtitle_hi': 'मिट्टी जांच',
  'icon': 'spa',
},
{
  'sr': '61',
  'id': 'green_house',
  'title_en': 'Green House Subsidy Rajasthan',
  'title_hi': 'ग्रीन हाउस सब्सिडी राजस्थान',
  'subtitle_en': 'Protected Farming',
  'subtitle_hi': 'संरक्षित खेती',
  'icon': 'house',
},
{
  'sr': '62',
  'id': 'acabc',
  'title_en': 'Agri Clinics & Agri Business Centres',
  'title_hi': 'कृषि क्लिनिक एवं कृषि व्यवसाय केंद्र',
  'subtitle_en': 'Agri Business Support',
  'subtitle_hi': 'कृषि व्यवसाय सहायता',
  'icon': 'business_center',
},
  ];

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final lang = context.watch<LanguageProvider>().currentLanguage;

    return MainShellScreen(
      currentItem: CustomBottomBarItem.dashboard,
      child: Scaffold(
        backgroundColor: theme.scaffoldBackgroundColor,

        // 🔹 App Bar
        appBar: CustomAppBar(
          title: lang == 'en' ? 'Government Schemes' : 'सरकारी योजनाएं',
          showBackButton: true,
        ),

        // 🔹 Body
        body: ListView.builder(
          padding: EdgeInsets.all(4.w),
          itemCount: schemes.length,
          itemBuilder: (context, index) {
            final scheme = schemes[index];

            return GestureDetector(
              onTap: () {
                Navigator.pushNamed(
  context,
  AppRoutes.schemeDetail,
  arguments: scheme['id'], // 👈 ONLY STRING
);
              },
              child: Container(
                margin: EdgeInsets.only(bottom: 2.h),
                padding: EdgeInsets.all(4.w),
                decoration: BoxDecoration(
                  color: theme.colorScheme.surface,
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.05),
                      blurRadius: 10,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Row(
                  children: [
                    Container(
                      padding: EdgeInsets.all(3.w),
                      decoration: BoxDecoration(
                        color: theme.colorScheme.primary.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: CustomIconWidget(
                        iconName: scheme['icon'],
                        color: theme.colorScheme.primary,
                        size: 28,
                      ),
                    ),
                    SizedBox(width: 4.w),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            lang == 'en'
                                ? scheme['title_en']
                                : scheme['title_hi'],
                            style: theme.textTheme.titleMedium?.copyWith(
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                          SizedBox(height: 0.5.h),
                          Text(
                            lang == 'en'
                                ? scheme['subtitle_en']
                                : scheme['subtitle_hi'],
                            style: theme.textTheme.bodySmall?.copyWith(
                              color: theme.colorScheme.onSurface.withOpacity(0.7),
                            ),
                          ),
                        ],
                      ),
                    ),
                    Icon(
                      Icons.arrow_forward_ios,
                      size: 16,
                      color: theme.colorScheme.onSurface.withOpacity(0.4),
                    ),
                  ],
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}