// File generated by FlutterFire CLI & customized for KrishiMitra AI.
// Replace this file with the output of `flutterfire configure` after setting
// up a real Firebase project.
//
// To set up Firebase:
//   1. Create a project at https://console.firebase.google.com
//   2. Install the FlutterFire CLI: `dart pub global activate flutterfire_cli`
//   3. Run: `flutterfire configure`  — this overwrites this file automatically.
//
// Until then, this stub prevents compilation errors while allowing the app
// to build and run in offline / demo mode.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'reconfigure with FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---------------------------------------------------------------------------
  // PLACEHOLDER VALUES — replace with real values from Firebase Console
  // ---------------------------------------------------------------------------

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '639200881122',
    projectId: 'krishimitra-ai-ec9d7',
    authDomain: 'krishimitra-ai-ec9d7.firebaseapp.com',
    storageBucket: 'krishimitra-ai-ec9d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbf9nG9DzXRH4-tduexrx3Pk-TRDByHw',
    appId: '1:639200881122:android:d111e655b8dfbd2925f1bb',
    messagingSenderId: '639200881122',
    projectId: 'krishimitra-ai-ec9d7',
    storageBucket: 'krishimitra-ai-ec9d7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '639200881122',
    projectId: 'krishimitra-ai-ec9d7',
    storageBucket: 'krishimitra-ai-ec9d7.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_REAL_IOS_CLIENT_ID',
    iosBundleId: 'com.krishimitra.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '639200881122',
    projectId: 'krishimitra-ai-ec9d7',
    storageBucket: 'krishimitra-ai-ec9d7.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_REAL_IOS_CLIENT_ID',
    iosBundleId: 'com.krishimitra.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_WITH_REAL_API_KEY',
    appId: '1:000000000000:windows:0000000000000000000000',
    messagingSenderId: '639200881122',
    projectId: 'krishimitra-ai-ec9d7',
    storageBucket: 'krishimitra-ai-ec9d7.firebasestorage.app',
  );
}
